management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

server:
  port: 650
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/novel_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: test123456
    driver-class-name: com.mysql.cj.jdbc.Driver  
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.243.172:8848  
        namespace: 3960c71a-62ac-4b8f-8c30-bba8e8143a0c
  
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /novel-plus
    template:
      # 缺省的交换机名称，此处配置后，发送消息如果不指定交换机就会使用这个
      exchange: novel.exchange
    publisher-confirms: false