spring: 
  rabbitmq:
    host: 47.106.243.172
    username: guest
    password: guest
    virtual-host: /novel-cloud
    template:
      # 缺省的交换机名称，此处配置后，发送消息如果不指定交换机就会使用这个
      exchange: novel.exchange
    publisher-confirms: false